language: c

dist: trusty

arch:
  - amd64
  - ppc64le

addons:
  apt:
    packages:
    - libssl-dev
    - libcurl4-openssl-dev
    - libjansson-dev
    - libhiredis-dev
    - libpcre3-dev
    - apache2-dev
    - check

install:
  - wget https://github.com/cisco/cjose/archive/0.5.1.tar.gz
  - tar zxvf 0.5.1.tar.gz
  - cd cjose-0.5.1
  - ./configure --prefix=/usr
  - make test
  - sudo make install
  - cd -

script:
  - ./autogen.sh && ./configure --with-apxs2=/usr/bin/apxs2 CFLAGS=-Werror && make && make test
